/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRandomMethodInArrayShift(){
      ArrayShift testingObject = new ArrayShift();
      assertTrue("testMethod should return true", testingObject.testMethod() );
    }

    @Test public void testDuckDuckGame(){
      List<String> list = new ArrayList<>();
      list.add("bob");
      list.add("james");
      list.add("cris");
      list.add("ed");
      list.add("amilia");

      System.out.println(list);
      System.out.println(Library.duckDuckGoose(list,3));
    }
}
